package com.example.InstaPay_Travel_Tours.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.math.BigDecimal;

@Entity // This annotation marks the class as a JPA entity, indicating it will be mapped to a table in the database.
public class Income {

    @Id // This annotation marks the 'id' field as the primary key of the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This annotation indicates that the 'id' field is auto-generated by the database (in this case, using identity).
    private Long id;

    private String description; // Field to store the description of the income

    private BigDecimal amount; // Field to store the amount of the income, using BigDecimal for precise calculations

    // Getters and Setters for the fields

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}
